import { defineField, defineType } from "sanity";

export const project = defineType({
  name: "project",
  title: "Project",
  type: "document",
  groups: [
    { name: "listing", title: "Listing", default: true },
    { name: "hero", title: "Hero" },
    { name: "specs", title: "Specifications" },
    { name: "highlights", title: "Highlights" },
    { name: "craft", title: "Craftsmanship" },
    { name: "gallery", title: "Gallery & tour" },
  ],
  fields: [
    defineField({
      name: "name",
      title: "Name",
      type: "string",
      group: "listing",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "listing",
      options: { source: "name", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({ name: "location", title: "Location", type: "string", group: "listing" }),
    defineField({ name: "year", title: "Year", type: "string", group: "listing" }),
    defineField({ name: "scale", title: "Scale", type: "string", group: "listing", description: "Used on the projects mosaic overlay" }),
    defineField({ name: "note", title: "Architect's Note", type: "text", group: "listing" }),
    defineField({
      name: "image",
      title: "Listing image",
      type: "image",
      group: "listing",
      options: { hotspot: true },
    }),
    defineField({
      name: "order",
      title: "Display Order",
      type: "number",
      group: "listing",
      description: "1 = first in grid",
    }),
    defineField({
      name: "intro",
      title: "Intro",
      type: "text",
      group: "hero",
      rows: 4,
    }),
    defineField({
      name: "sketch",
      title: "Technical sketch",
      type: "image",
      group: "hero",
      options: { hotspot: true },
    }),
    defineField({
      name: "specs",
      title: "Specifications",
      type: "object",
      group: "specs",
      fields: [
        defineField({ name: "plot", title: "Plot", type: "string" }),
        defineField({ name: "dimensions", title: "Dimensions", type: "string" }),
        defineField({ name: "bhk", title: "BHK", type: "string" }),
        defineField({ name: "facing", title: "Face", type: "string" }),
        defineField({ name: "solar", title: "Solar", type: "string" }),
        defineField({
          name: "status",
          title: "Status",
          type: "string",
          options: {
            list: [
              { title: "Upcoming", value: "upcoming" },
              { title: "Ongoing", value: "ongoing" },
              { title: "Completed", value: "completed" },
            ],
            layout: "radio",
          },
        }),
        defineField({ name: "startDate", title: "Start", type: "string", description: "e.g. JUL 2024" }),
        defineField({ name: "endDate", title: "End", type: "string", description: "e.g. DEC 2025" }),
      ],
    }),
    defineField({
      name: "highlightsTitle",
      title: "Highlights title",
      type: "string",
      group: "highlights",
      initialValue: "Architectural Highlights & Spatial Design",
    }),
    defineField({
      name: "highlights",
      title: "Highlights",
      type: "array",
      group: "highlights",
      of: [
        {
          type: "object",
          name: "highlight",
          fields: [
            defineField({ name: "title", title: "Title", type: "string", validation: (Rule) => Rule.required() }),
            defineField({ name: "body", title: "Body", type: "text", rows: 3 }),
          ],
          preview: { select: { title: "title", subtitle: "body" } },
        },
      ],
    }),
    defineField({
      name: "highlightsImage",
      title: "Highlights image",
      type: "image",
      group: "highlights",
      options: { hotspot: true },
    }),
    defineField({
      name: "craftTitle",
      title: "Craftsmanship title",
      type: "string",
      group: "craft",
      initialValue: "Craftsmanship & Quality",
    }),
    defineField({
      name: "craftBody",
      title: "Craftsmanship body",
      type: "text",
      group: "craft",
      rows: 8,
    }),
    defineField({
      name: "craftImage",
      title: "Craftsmanship image",
      type: "image",
      group: "craft",
      options: { hotspot: true },
    }),
    defineField({
      name: "galleryFeatured",
      title: "Featured gallery image",
      type: "image",
      group: "gallery",
      options: { hotspot: true },
      description: "Large tile. If empty, the first gallery image is used.",
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      group: "gallery",
      of: [
        {
          type: "image",
          options: { hotspot: true },
          fields: [{ name: "caption", title: "Caption", type: "string" }],
        },
      ],
    }),
    defineField({
      name: "tourTitle",
      title: "Home tour title",
      type: "string",
      group: "gallery",
      initialValue: "Home Tour",
    }),
    defineField({
      name: "tourVideoUrl",
      title: "Home tour video URL",
      type: "url",
      group: "gallery",
    }),
  ],
  orderings: [{ title: "Display Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: {
    select: { title: "name", subtitle: "location", media: "image" },
  },
});
